###############################################################
#  Generated by:      Cadence Innovus 21.17-s075_1
#  OS:                Linux x86_64(Host ID vlsi413)
#  Generated on:      Tue Dec  3 16:43:50 2024
#  Design:            riscv_core
#  Command:           saveDesign -cellview {riscv_core  riscv_core  layout}
###############################################################
current_design riscv_core
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
